wandb_version: 1

alpha:
  value: 0.6
extn:
  value: _run_1
joint_proj:
  value: no_proj
lr:
  value: 5.0e-06
mask_where:
  value: clipAttn
ne:
  value: 3
output_grid_h:
  value: 12
output_grid_w:
  value: 24
percent_data:
  value: 1
